name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build all targets
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            builds/MontageGo-darwin-amd64
            builds/MontageGo-darwin-arm64
            builds/MontageGo-linux-amd64
            builds/MontageGo-windows-amd64.exe
            builds/config.sample.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
